// <auto-generated />
using System;
using Business.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Business.Infrastructure.Migrations.Restaurant
{
    [DbContext(typeof(BusinessDbContext))]
    [Migration("20260831054105_PrefixRestaurantTables")]
    partial class PrefixRestaurantTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Business.Domain.Entities.RateLimitPolicy", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<uint?>("BurstLimit")
                        .HasColumnType("int unsigned");

                    b.Property<string>("HttpMethods")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PartitionBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<uint>("PermitLimit")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RoutePattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("Version")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("WindowSeconds")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("restaurant_rate_limit_policies", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Category", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<ulong?>("ParentId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uk_categories_code");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_categories_active_order");

                    b.HasIndex("ParentId", "DisplayOrder", "Name")
                        .HasDatabaseName("ix_categories_parent_order");

                    b.ToTable("restaurant_categories", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Food", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("CategoryId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uk_foods_code");

                    b.HasIndex("CategoryId", "IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_foods_category_active");

                    b.ToTable("restaurant_foods", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.FoodPriceHistory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong>("FoodVariantId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodVariantId", "EffectiveFrom", "EffectiveTo")
                        .HasDatabaseName("ix_food_price_histories_variant_dates");

                    b.ToTable("restaurant_food_price_histories", null, t =>
                        {
                            t.HasCheckConstraint("chk_food_price_histories_dates", "EffectiveTo IS NULL OR EffectiveTo > EffectiveFrom");

                            t.HasCheckConstraint("chk_food_price_histories_price", "Price >= 0");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.FoodVariant", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal>("CurrentPrice")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<ulong>("FoodId")
                        .HasColumnType("bigint unsigned");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SoldOutReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId", "Code")
                        .IsUnique()
                        .HasDatabaseName("uk_food_variants_food_code");

                    b.HasIndex("FoodId", "IsActive", "IsAvailable", "DisplayOrder")
                        .HasDatabaseName("ix_food_variants_food_available");

                    b.ToTable("restaurant_food_variants", null, t =>
                        {
                            t.HasCheckConstraint("chk_food_variants_price", "CurrentPrice >= 0");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.KitchenOrder", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("AcceptedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("AcceptedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("KitchenNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<ulong>("OrderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("ReadyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("SentToKitchenDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("KitchenNo")
                        .IsUnique()
                        .HasDatabaseName("uk_kitchen_orders_kitchen_no");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_kitchen_orders_order");

                    b.HasIndex("Status", "SentToKitchenDate")
                        .HasDatabaseName("ix_kitchen_orders_status_sent");

                    b.ToTable("restaurant_kitchen_orders", null, t =>
                        {
                            t.HasCheckConstraint("chk_kitchen_orders_status", "Status IN ('Pending','Accepted','Preparing','Ready','Completed','Rejected','Cancelled')");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.KitchenOrderItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<ulong>("KitchenOrderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<ulong>("OrderItemId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<DateTime?>("ReadyDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("StartedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("OrderItemId")
                        .HasDatabaseName("ix_kitchen_order_items_order_item");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_kitchen_order_items_status");

                    b.HasIndex("KitchenOrderId", "OrderItemId")
                        .IsUnique()
                        .HasDatabaseName("uk_kitchen_order_items_pair");

                    b.ToTable("restaurant_kitchen_order_items", null, t =>
                        {
                            t.HasCheckConstraint("chk_kitchen_order_items_quantity", "Quantity > 0");

                            t.HasCheckConstraint("chk_kitchen_order_items_status", "Status IN ('Pending','Accepted','Preparing','Ready','Completed','Rejected','Cancelled')");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Order", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<ulong?>("CustomerId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("OrderNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("OrderType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("DineIn");

                    b.Property<DateTime>("OrderedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("SubtotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<ulong?>("TableSessionId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("TaxAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<decimal>("TotalAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_orders_customer");

                    b.HasIndex("OrderNo")
                        .IsUnique()
                        .HasDatabaseName("uk_orders_order_no");

                    b.HasIndex("TableSessionId")
                        .HasDatabaseName("ix_orders_table_session");

                    b.HasIndex("OrderedDate", "Status")
                        .HasDatabaseName("ix_orders_ordered_date_status");

                    b.ToTable("restaurant_orders", null, t =>
                        {
                            t.HasCheckConstraint("chk_orders_amounts", "SubtotalAmount >= 0 AND DiscountAmount >= 0 AND TaxAmount >= 0 AND TotalAmount >= 0");

                            t.HasCheckConstraint("chk_orders_status", "Status IN ('Draft','Pending','Confirmed','Serving','Completed','Cancelled')");

                            t.HasCheckConstraint("chk_orders_type", "OrderType IN ('DineIn','TakeAway','Delivery')");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderItem", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal>("DiscountAmount")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasDefaultValue(0m);

                    b.Property<string>("FoodCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong>("FoodId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<ulong>("FoodVariantId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<ulong>("OrderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<string>("VariantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_order_items_food");

                    b.HasIndex("FoodVariantId")
                        .HasDatabaseName("ix_order_items_variant");

                    b.HasIndex("OrderId", "Status")
                        .HasDatabaseName("ix_order_items_order_status");

                    b.ToTable("restaurant_order_items", null, t =>
                        {
                            t.HasCheckConstraint("chk_order_items_amounts", "UnitPrice >= 0 AND DiscountAmount >= 0 AND TotalAmount >= 0");

                            t.HasCheckConstraint("chk_order_items_quantity", "Quantity > 0");

                            t.HasCheckConstraint("chk_order_items_status", "Status IN ('Pending','Accepted','Preparing','Ready','Served','Completed','Cancelled','Rejected')");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderItemKitchenQuantity", b =>
                {
                    b.Property<ulong>("OrderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("OrderItemId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("OrderedQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.Property<decimal>("SentQuantity")
                        .HasPrecision(18, 3)
                        .HasColumnType("decimal(18,3)");

                    b.ToTable((string)null);

                    b.ToView("restaurant_order_item_kitchen_quantities", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderPaymentBalance", b =>
                {
                    b.Property<ulong>("OrderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<ulong?>("TableSessionId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("restaurant_order_payment_balances", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderPromotion", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<ulong>("OrderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("PromotionCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong>("PromotionId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("PromotionId")
                        .HasDatabaseName("ix_order_promotions_promotion");

                    b.HasIndex("OrderId", "PromotionId")
                        .IsUnique()
                        .HasDatabaseName("uk_order_promotions_order_promotion");

                    b.ToTable("restaurant_order_promotions", null, t =>
                        {
                            t.HasCheckConstraint("chk_order_promotions_discount", "DiscountAmount >= 0");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderStatusHistory", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("ChangedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("ChangedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<ulong>("OrderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("ToStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId", "ChangedDate")
                        .HasDatabaseName("ix_order_status_histories_order_date");

                    b.ToTable("restaurant_order_status_histories", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Payment", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Pending");

                    b.Property<ulong>("TableSessionId")
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("TransactionNo")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("TransactionNo")
                        .HasDatabaseName("ix_payments_transaction_no");

                    b.HasIndex("PaidDate", "Status")
                        .HasDatabaseName("ix_payments_paid_date_status");

                    b.HasIndex("TableSessionId", "Status")
                        .HasDatabaseName("ix_payments_session_status");

                    b.ToTable("restaurant_payments", null, t =>
                        {
                            t.HasCheckConstraint("chk_payments_amount", "Amount > 0");

                            t.HasCheckConstraint("chk_payments_method", "PaymentMethod IN ('Cash','Card','BankTransfer','Momo','VNPay','Other')");

                            t.HasCheckConstraint("chk_payments_status", "Status IN ('Pending','Paid','Failed','Refunded','Cancelled')");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.PaymentAllocation", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<ulong>("OrderId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("PaymentId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_payment_allocations_order");

                    b.HasIndex("PaymentId", "OrderId")
                        .IsUnique()
                        .HasDatabaseName("uk_payment_allocations_payment_order");

                    b.ToTable("restaurant_payment_allocations", null, t =>
                        {
                            t.HasCheckConstraint("chk_payment_allocations_amount", "Amount > 0");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.PromotionCategory", b =>
                {
                    b.Property<ulong>("PromotionId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("CategoryId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("PromotionId", "CategoryId");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_promotion_categories_category");

                    b.ToTable("restaurant_promotion_categories", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.PromotionCode", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("DiscountType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<decimal>("DiscountValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<decimal?>("MaxDiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.Property<int>("UsageCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int?>("UsageLimit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uk_promotion_codes_code");

                    b.HasIndex("IsActive", "StartDate", "EndDate")
                        .HasDatabaseName("ix_promotion_codes_validity");

                    b.ToTable("restaurant_promotion_codes", null, t =>
                        {
                            t.HasCheckConstraint("chk_promotion_codes_dates", "EndDate > StartDate");

                            t.HasCheckConstraint("chk_promotion_codes_type", "DiscountType IN ('Percentage','FixedAmount')");

                            t.HasCheckConstraint("chk_promotion_codes_usage", "UsageLimit IS NULL OR UsageLimit >= 0");

                            t.HasCheckConstraint("chk_promotion_codes_usage_count", "UsageCount >= 0");

                            t.HasCheckConstraint("chk_promotion_codes_value", "DiscountValue > 0");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.PromotionFood", b =>
                {
                    b.Property<ulong>("PromotionId")
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("FoodId")
                        .HasColumnType("bigint unsigned");

                    b.HasKey("PromotionId", "FoodId");

                    b.HasIndex("FoodId")
                        .HasDatabaseName("ix_promotion_foods_food");

                    b.ToTable("restaurant_promotion_foods", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.RestaurantArea", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uk_restaurant_areas_code");

                    b.HasIndex("IsActive", "DisplayOrder")
                        .HasDatabaseName("ix_restaurant_areas_active_order");

                    b.ToTable("restaurant_areas", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.RestaurantTable", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong>("AreaId")
                        .HasColumnType("bigint unsigned");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<ulong?>("CreatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Available");

                    b.Property<ulong?>("UpdatedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("uk_restaurant_tables_code");

                    b.HasIndex("AreaId", "Status", "IsActive")
                        .HasDatabaseName("ix_restaurant_tables_area_status");

                    b.ToTable("restaurant_tables", null, t =>
                        {
                            t.HasCheckConstraint("chk_restaurant_tables_capacity", "Capacity > 0");

                            t.HasCheckConstraint("chk_restaurant_tables_status", "Status IN ('Available','Occupied','Reserved','Cleaning','Disabled')");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.TableSession", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<ulong?>("ClosedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime?>("ClosedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("GuestCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<ulong?>("OpenedBy")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("OpenedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasDefaultValue("Open");

                    b.Property<ulong>("TableId")
                        .HasColumnType("bigint unsigned");

                    b.Property<DateTime>("UpdatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)");

                    b.HasKey("Id");

                    b.HasIndex("OpenedDate")
                        .HasDatabaseName("ix_table_sessions_opened_date");

                    b.HasIndex("TableId", "Status")
                        .HasDatabaseName("ix_table_sessions_table_status");

                    b.ToTable("restaurant_table_sessions", null, t =>
                        {
                            t.HasCheckConstraint("chk_table_sessions_guest_count", "GuestCount > 0");

                            t.HasCheckConstraint("chk_table_sessions_status", "Status IN ('Open','Closed','Cancelled')");
                        });
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.TableSessionPaymentBalance", b =>
                {
                    b.Property<decimal>("PaidAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("RemainingAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<ulong>("TableSessionId")
                        .HasColumnType("bigint unsigned");

                    b.Property<decimal>("TotalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.ToTable((string)null);

                    b.ToView("restaurant_table_session_payment_balances", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Category", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_categories_parent");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Food", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Category", "Category")
                        .WithMany("Foods")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_foods_category");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.FoodPriceHistory", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.FoodVariant", "FoodVariant")
                        .WithMany("PriceHistories")
                        .HasForeignKey("FoodVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_food_price_histories_variant");

                    b.Navigation("FoodVariant");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.FoodVariant", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Food", "Food")
                        .WithMany("Variants")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_food_variants_food");

                    b.Navigation("Food");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.KitchenOrder", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Order", "Order")
                        .WithMany("KitchenOrders")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kitchen_orders_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.KitchenOrderItem", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.KitchenOrder", "KitchenOrder")
                        .WithMany("Items")
                        .HasForeignKey("KitchenOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kitchen_order_items_kitchen_order");

                    b.HasOne("Business.Domain.Entities.Restaurant.OrderItem", "OrderItem")
                        .WithMany("KitchenOrderItems")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kitchen_order_items_order_item");

                    b.Navigation("KitchenOrder");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Order", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.TableSession", "TableSession")
                        .WithMany("Orders")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_table_session");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderItem", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Food", "Food")
                        .WithMany("OrderItems")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_food");

                    b.HasOne("Business.Domain.Entities.Restaurant.FoodVariant", "FoodVariant")
                        .WithMany("OrderItems")
                        .HasForeignKey("FoodVariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_variant");

                    b.HasOne("Business.Domain.Entities.Restaurant.Order", "Order")
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_items_order");

                    b.Navigation("Food");

                    b.Navigation("FoodVariant");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderPromotion", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Order", "Order")
                        .WithMany("Promotions")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_promotions_order");

                    b.HasOne("Business.Domain.Entities.Restaurant.PromotionCode", "Promotion")
                        .WithMany("OrderPromotions")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_promotions_promotion");

                    b.Navigation("Order");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderStatusHistory", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Order", "Order")
                        .WithMany("StatusHistories")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_status_histories_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Payment", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.TableSession", "TableSession")
                        .WithMany("Payments")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payments_table_session");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.PaymentAllocation", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Order", "Order")
                        .WithMany("PaymentAllocations")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_payment_allocations_order");

                    b.HasOne("Business.Domain.Entities.Restaurant.Payment", "Payment")
                        .WithMany("Allocations")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_payment_allocations_payment");

                    b.Navigation("Order");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.PromotionCategory", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Category", "Category")
                        .WithMany("PromotionCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_categories_category");

                    b.HasOne("Business.Domain.Entities.Restaurant.PromotionCode", "Promotion")
                        .WithMany("PromotionCategories")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_categories_promotion");

                    b.Navigation("Category");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.PromotionFood", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.Food", "Food")
                        .WithMany("PromotionFoods")
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_foods_food");

                    b.HasOne("Business.Domain.Entities.Restaurant.PromotionCode", "Promotion")
                        .WithMany("PromotionFoods")
                        .HasForeignKey("PromotionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_promotion_foods_promotion");

                    b.Navigation("Food");

                    b.Navigation("Promotion");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.RestaurantTable", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.RestaurantArea", "Area")
                        .WithMany("Tables")
                        .HasForeignKey("AreaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_restaurant_tables_area");

                    b.Navigation("Area");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.TableSession", b =>
                {
                    b.HasOne("Business.Domain.Entities.Restaurant.RestaurantTable", "Table")
                        .WithMany("Sessions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_table_sessions_table");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Category", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Foods");

                    b.Navigation("PromotionCategories");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Food", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("PromotionFoods");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.FoodVariant", b =>
                {
                    b.Navigation("OrderItems");

                    b.Navigation("PriceHistories");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.KitchenOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Order", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("KitchenOrders");

                    b.Navigation("PaymentAllocations");

                    b.Navigation("Promotions");

                    b.Navigation("StatusHistories");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.OrderItem", b =>
                {
                    b.Navigation("KitchenOrderItems");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Payment", b =>
                {
                    b.Navigation("Allocations");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.PromotionCode", b =>
                {
                    b.Navigation("OrderPromotions");

                    b.Navigation("PromotionCategories");

                    b.Navigation("PromotionFoods");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.RestaurantArea", b =>
                {
                    b.Navigation("Tables");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.RestaurantTable", b =>
                {
                    b.Navigation("Sessions");
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.TableSession", b =>
                {
                    b.Navigation("Orders");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
