// <auto-generated />
using Business.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Business.Infrastructure.Migrations.Restaurant
{
    [DbContext(typeof(BusinessDbContext))]
    [Migration("20260825053918_RestaurantInitial")]
    partial class RestaurantInitial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Business.Domain.Entities.RateLimitPolicy", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned");

                    b.Property<string>("Algorithm")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.Property<uint?>("BurstLimit")
                        .HasColumnType("int unsigned");

                    b.Property<string>("HttpMethods")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PartitionBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<uint>("PermitLimit")
                        .HasColumnType("int unsigned");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RoutePattern")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<ulong>("Version")
                        .HasColumnType("bigint unsigned");

                    b.Property<uint>("WindowSeconds")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("rate_limit_policies", (string)null);
                });

            modelBuilder.Entity("Business.Domain.Entities.Restaurant.Product", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Code");

                    b.ToTable("restaurant_products", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
